chore: use newer GitHub issue forms
pypa/packaging-problems pull request #532
Opened 2021-07-12 02:55 UTC by henryiii

This would help with #481 by adding a custom issue form, preview viewable here: https://github.com/henryiii/packaging-problems/issues/new?template=help_request.yml&title=Trouble+with+packaging+tutorial (a similar link would be swapped out in packaging.python.org, the `?template=help_request.yml&title=Trouble+with+packaging+tutorial` part could to be added to avoid an extra step clicking the only template. Issue forms do not seem to work if they are the only  item, but only inside the ISSUE_TEMPLATE folder.)

This will help prompt users to a) not submit unless at least the description has something in it, and b) get nicer (and hopefully more often complete) tracebacks. (I think)

2021-07-12 02:59 UTC, henryiii commented
I filled in the the template to see what it would produce, you can see the result here: https://github.com/henryiii/packaging-problems/issues/1

The textbox with the `pytb` setting actually uses a monospace font, very nice attention to detail.

2021-07-12 09:13 UTC, layday commented
That looks great. I imagine we'd still want to allow form-less issues though. You have to set `blank_issues_enabled` to `true` in `.github/ISSUE_TEMPLATE/config.yaml` for that.

2021-07-12 14:42 UTC, henryiii commented
I'm 99% sure that's the default. You only need that file to turn off blank issues or add custom links to the choices. See the linked example site:

<img width="763" alt="Screen Shot 2021-07-12 at 10 40 18 AM" src="https://user-images.githubusercontent.com/4616906/125307161-d26e9d80-e2fd-11eb-99b0-ad6923c432ed.png">

2021-07-12 14:44 UTC, henryiii commented
PS, forgot to mention it earlier, but I tried to stay very close to the spirit of the original template; having a spot to paste the results of `pip list` or something like that might be a future improvement, but I was mostly interested in just converting the original to a form.

2021-07-12 14:45 UTC, henryiii commented on .github/issue_template.md
> -<!-- Your pip version, for example pip 19.2. You can usually get this by running `python -m pip --vesion` -->
This type (`--vesion`) has been here for years. :)

2021-07-12 15:00 UTC, layday commented
> I'm 99% sure that's the default. You only need that file to turn off blank issues or add custom links to the choices. See the linked example site:

Ok, I did not spot that at all.  Terrible UX.

2021-07-12 16:35 UTC, henryiii commented
You could probably add an entry in the list that says "blank" and then link to the place this link takes you. But this is the standard place for that on GitHub (and hopefully people opening a blank issue know what they are doing, I'd think?).

2021-07-13 01:06 UTC, bhrutledge requested changes
Thanks for this! I love the direction, but want to clarify the intent. While the vast majority of issues reported here are related to the packaging projects tutorial, there are others. I've also been thinking about opening an issue/PR on packaging.python.org to add more links to create an issue on this repo, so a more general issue template would be useful.

We could make the issue template specific to the packaging projects tutorial, but it doesn't seem like that would scale well....

I'd also love to get @pradyunsg's thoughts, since he opened the original issue, and has experience with this on pip: https://github.com/pypa/pip/issues/new/choose

2021-07-13 01:06 UTC, bhrutledge commented on .github/ISSUE_TEMPLATE/help_request.yml
> +    render: pytb
Will this always be a Python traceback? For example, could it be a custom error message, formatted by the command-line tool? Assuming so, I'd make the `id`, `description`, and `render` more generic.

2021-07-23 20:06 UTC, henryiii commented on .github/ISSUE_TEMPLATE/help_request.yml
> +title: Trouble with packaging tutorial
The idea was this template was specifically for users coming in from the tutorial, where this is repo is currently linked. If we have more entry points, we could have more templates. And we could have a general "template" in addition to this form.

2021-07-23 20:08 UTC, henryiii commented on .github/ISSUE_TEMPLATE/help_request.yml
> +    placeholder: Python 0.0.0
I feel like any real number will tend to make a user want to use that instead of figuring it out, and setting a real version will either require constant updating or will quickly look dated.

2021-07-23 20:09 UTC, henryiii commented on .github/ISSUE_TEMPLATE/help_request.yml
> +    value: https://packaging.python.org/tutorials/packaging-projects
I was waffling between that and this, I can switch.

2021-07-23 20:11 UTC, henryiii commented on .github/ISSUE_TEMPLATE/help_request.yml
> +    render: pytb
There's no harm in trying to render random text as a traceback, and we can always remove it. It's best to target what is most common, and most commonly, this is a traceback. We can always removed the `pytb` from the issue if it doesn't apply and makes the text less appealing. But this should be more often right then not.

2021-07-23 20:12 UTC, henryiii commented
The goal of the form is to help 90% of the issues here, the ones that take work to address, easier to address with more and better formatted information. I'll add a separate "general" issue and generalize this slight, but it's not supposed to be super-general, that defeats the point of a form over a textbox.

2021-07-23 20:22 UTC, henryiii commented on .github/ISSUE_TEMPLATE/help_request.yml
> +title: Trouble with packaging tutorial
Added a general template, and generalized this one a bit.

2021-07-23 20:23 UTC, henryiii commented on .github/ISSUE_TEMPLATE/help_request.yml
> +    placeholder: Python 0.0.0
Used x.x.x here instead. Maybe better?

2021-07-23 20:25 UTC, henryiii commented on .github/ISSUE_TEMPLATE/help_request.yml
> +    placeholder: Python 0.0.0
Also they are now required. So if someone leaves them alone, GitHub will tell them to fill them in.

2021-07-23 21:14 UTC, pradyunsg reviewed
LGTM, with a non-blocking suggestion.

I am pretty sure the first time I touch this, I'm gonna reformat this with `prettier` to force consistent whitespace, trim trailing whitespace and all that boring stuff. :)

2021-07-23 21:14 UTC, pradyunsg commented on .github/ISSUE_TEMPLATE/packaging_tutorial.yml
> +      If following an online tutorial or guide, please provide a link to the page or section giving you trouble.
```suggestion
      If you are following an online tutorial or guide, please provide a link to the page or section giving you trouble.
```

2021-07-23 21:15 UTC, pradyunsg approved these changes
Clicked the wrong button the last time. :)

2021-07-24 10:40 UTC, bhrutledge requested changes
I like the updates; just a few more, please. 🙂

2021-07-24 10:40 UTC, bhrutledge commented on .github/ISSUE_TEMPLATE/packaging_tutorial.yml
> +      To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.
Given the number of required questions, this seems like a tease. 😉 

```suggestion
      To help us help you, please fill out as much of the following as you can. 
```

2021-07-24 10:40 UTC, bhrutledge commented on .github/ISSUE_TEMPLATE/packaging_tutorial.yml
> +      Please describe your problem, including all commands that you ran. Include any offline guides you followed, etc.
```suggestion
      Please describe your problem in as much detail as possible.
      
      Include all the commands that you ran, any offline guides you followed, etc.
```

2021-07-24 10:40 UTC, bhrutledge commented on .github/ISSUE_TEMPLATE/packaging_tutorial.yml
> +    render: pytb
> There's no harm in trying to render random text as a traceback, and we can always remove it. It's best to target what is most common, and most commonly, this is a traceback. We can always removed the pytb from the issue if it doesn't apply and makes the text less appealing. But this should be more often right then not.

As a general philosophy, I've started leaning towards "most inclusive" over "most common". With that in mind, I'd really rather generalize this.

```suggestion
- type: textarea
  id: error
  attributes:
    label: Error message
    description: |
      If you received an error message, please copy and paste the _entire_ message here.
    render: text
```

2021-07-24 10:40 UTC, bhrutledge commented on .github/ISSUE_TEMPLATE/packaging_tutorial.yml
> +title: Trouble with a packaging tutorial
I like that this is "_a_ packaging tutorial", not "_the_ packaging tutorial". IE, it's appropriate for multiple documents.

2021-07-26 20:19 UTC, henryiii commented
This would have stopped https://github.com/pypa/packaging-problems/issues/536 from being submitted without anything filled in, for example. ;)

2021-07-26 23:59 UTC, bhrutledge approved these changes
Thanks for taking my suggestions. Before merging, do you happen to know if this will break the existing links to create a new issue from the packaging tutorial? IE, should there be a ready-to-merge PR on that repo?

2021-07-27 01:12 UTC, henryiii commented
It shouldn't break anything, though we can have a ready to go PR there also.

2021-07-27 09:53 UTC, merged

2024-08-19 21:50 UTC, Leoporno commented on .github/issue_template.md
> -<!-- Your pip version, for example pip 19.2. You can usually get this by running `python -m pip --vesion` -->
Jw

2024-08-19 22:34 UTC, Leoporno approved these changes